#### DELETE SINGLE POST
DELETE http://localhost:5000/posts/15998523238920637

#### GET SINGLE POST
GET http://localhost:5000/posts/8374820193847912sasd

#### GET ALL POSTS
GET http://localhost:5000/posts

### CREATE POST
POST http://localhost:5000/posts
content-type: application/json

{
  "title": "Test Post",
  "body": "This is a test post.",
  "author": "John Doe",
  "tags": ["test", "example"],
  "date": "2022-04-03"
}

#### BAD CREATE POST
POST http://localhost:5000/posts
content-type: application/json

{
  "body": "This is a test post.",
  "author": "",
  "tags": "test, tes1",
  "date": "2022-04-03T12:00:00Z"
}


### 
GET http://localhost:5000/comments/9021793848917992

####
DELETE  http://localhost:5000/comments/845848428961611


####

POST http://localhost:5000/comments
content-type: application/json

{   
  "authorEmail": "james@bond.com",
  "text": "this is a test comment",
  "postId": "3083126839342818"
}

#### BAD CREATE POST

POST http://localhost:5000/posts
content-type: application/json

{
  
  "body": "This is a test post.",
  "author": "",
  "tags": "test, tes1",
  "date": "2022-04-03T12:00:00Z"
}

